# Generated by Django 2.0.2 on 2018-04-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='message_id',
            new_name='messageid',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='room_id',
            new_name='rommid',
        ),
    ]
