# Generated by Django 2.0.2 on 2018-04-24 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='', max_length=255)),
                ('messageid', models.CharField(max_length=255)),
                ('roomid', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_app.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('student_choice', models.IntegerField(default=1)),
                ('student_comment', models.CharField(max_length=500)),
                ('feedback_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.FeedbackSession')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_app.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
