# Generated by Django 2.0.2 on 2018-04-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentFeedbackManager',
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='student_choice',
            field=models.IntegerField(default=1),
        ),
    ]
