# Generated by Django 2.0.2 on 2018-04-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180423_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksession',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
    ]
